<?php
function lifestream_rss_feed()
{
    /**
     * Outputs an RSS feed of your lifestream activity.
     * @todo
     */
}

function lifestream_dump_opml()
{
    /**
     * Outputs an OPML feed which can be used to backup your lifestream settings.
     * @todo
     */
    global $wpdb;
    
    $date = date(DATE_RFC822);
    $lines = array('<?xml version="1.0" encoding="ISO-8859-1"?>');
    $lines[] = '<!-- OPML generated by LifeStream '.LIFESTREAM_VERSION.' on '.$date.' -->';
    $lines[] = '<opml version="1.1">';
    $lines[] = '    <head>';
    $lines[] = '        <title>lifestream.feeds</title>';
    $lines[] = '        <dateCreated>'.$date.'</dateCreated>';
    $lines[] = '        <dateModified>'.$date.'</dateModified>';
    $lines[] = '    </head>';
    $lines[] = '    <body>';
    $results =& $wpdb->get_results("SELECT * FROM `".$wpdb->prefix."lifestream_feeds`");
    foreach ($results as $result)
    {
        $instance = LifeStream_Feed::construct_from_query_result($result);
        if (method_exists($instance, 'get_url'))
        {
            $urls = $instance->get_url();
            if (!is_array($urls)) $urls = array($urls);
            $items = array();
            foreach ($urls as $url_data)
            {
                if (is_array($url_data))
                {
                    // url, key
                    list($url, $key) = $url_data;
                }
                else
                {
                    $url = $url_data;
                    $key = '';
                }
                $lines[] = '        <outline text="'.htmlspecialchars($instance->get_feed_display()).'" xmlUrl="'.$url.'" type="'.$instance->get_constant('ID').'"/>';
            }
        }
    }
    $lines[] = '    </body>';
    $lines[] = '</opml>';
    echo implode("\n", $lines);
}
?>